-- DELETE P1 FROM PERSON P1 
-- JOIN PERSON P2
-- ON P1.EMAIL = P2.EMAIL AND P1.ID > P2.ID;
DELETE FROM PERSON
WHERE ID NOT IN (
    SELECT * FROM(
        SELECT MIN(ID)
        FROM PERSON
        GROUP BY EMAIL
    )AS T
);