CREATE FUNCTION getNthHighestSalary(N INT) RETURNS INT
DETERMINISTIC
BEGIN
  SET N = N - 1;
  RETURN (
        SELECT DISTINCT SALARY FROM EMPLOYEE 
        ORDER BY SALARY DESC
        LIMIT 1 OFFSET N
  );
END